import {
  ArrowLeft,
  ArrowRight,
  Calendar,
  Camera,
  Check,
  ChevronDown,
  ChevronUp,
  Clock,
  Code,
  Copy,
  CreditCard,
  Download,
  Edit,
  Edit2,
  ExternalLink,
  File,
  FileText,
  Filter,
  Folder,
  FolderPlus,
  Github,
  GripVertical,
  Heart,
  HelpCircle,
  Home,
  Image,
  Laptop,
  Loader2,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Menu,
  MessageSquare,
  Mic,
  MicOff,
  Minus,
  MoreHorizontal,
  Move,
  Package,
  Pencil,
  Plus,
  PlusCircle,
  SignpostIcon as Post,
  Reply,
  Rocket,
  RotateCcw,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Shield,
  ShoppingCart,
  Slash,
  Sparkles,
  Star,
  Sun,
  Table,
  Terminal,
  Trash,
  Trash2,
  TrendingUp,
  Truck,
  Twitter,
  Upload,
  User,
  UserPlus,
  Users,
  Video,
  View,
  X,
  XCircle,
  AlertTriangle,
  UploadCloud,
  Eye,
  EyeOff,
  LayoutDashboard,
  LayoutList,
  LayoutGrid,
  Layout,
  LayoutPanelLeft,
  LayoutPanelTop,
  LayoutTemplate,
  LayoutGridIcon as LayoutColumns,
  Store,
  Shirt,
  Gift,
} from "lucide-react"

import type { LucideIcon } from "lucide-react"

type Icon = LucideIcon

export const Icons = {
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  calendar: Calendar,
  camera: Camera,
  check: Check,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  clock: Clock,
  code: Code,
  copy: Copy,
  creditCard: CreditCard,
  download: Download,
  edit: Edit,
  edit2: Edit2,
  externalLink: ExternalLink,
  file: File,
  fileText: FileText,
  filter: Filter,
  folder: Folder,
  folderPlus: FolderPlus,
  github: Github,
  gripVertical: GripVertical,
  heart: Heart,
  helpCircle: HelpCircle,
  home: Home,
  image: Image,
  laptop: Laptop,
  loader2: Loader2,
  lock: Lock,
  logOut: LogOut,
  mail: Mail,
  mapPin: MapPin,
  menu: Menu,
  messageSquare: MessageSquare,
  mic: Mic,
  micOff: MicOff,
  minus: Minus,
  moreHorizontal: MoreHorizontal,
  move: Move,
  package: Package,
  pencil: Pencil,
  plus: Plus,
  plusCircle: PlusCircle,
  post: Post,
  reply: Reply,
  rocket: Rocket,
  rotateCcw: RotateCcw,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  share2: Share2,
  shield: Shield,
  spinner: Loader2,
  shoppingCart: ShoppingCart,
  slash: Slash,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  table: Table,
  terminal: Terminal,
  trash: Trash,
  trash2: Trash2,
  trendingUp: TrendingUp,
  truck: Truck,
  twitter: Twitter,
  upload: Upload,
  user: User,
  userPlus: UserPlus,
  users: Users,
  video: Video,
  view: View,
  x: X,
  xCircle: XCircle,
  alertTriangle: AlertTriangle,
  uploadCloud: UploadCloud,
  eye: Eye,
  eyeOff: EyeOff,
  layoutDashboard: LayoutDashboard,
  layoutList: LayoutList,
  layoutGrid: LayoutGrid,
  layout: Layout,
  layoutPanelLeft: LayoutPanelLeft,
  layoutPanelTop: LayoutPanelTop,
  layoutTemplate: LayoutTemplate,
  layoutColumns: LayoutColumns,
  store: Store,
  shirt: Shirt,
  gift: Gift,
}
